.PHONY: clean
.PHONY: d3-vis
.PHONY: visualization

clean:
	rm -rf models
	rm -rf figures
	rm -rf derived_data
	rm -rf .created-dirs
	rm -f writeup.pdf

.created-dirs:
	mkdir -p models
	mkdir -p figures
	mkdir -p derived_data
	touch .created-dirs

# check out the dataset and eprform cleaning
derived_data/data_df.csv: .created-dirs df.R source_data/data.csv
	Rscript df.R



# Start a server for the cleaned dataset
visualization: derived_data/data_df.csv 
	lighttpd -D -f lighttpd.conf

# Build the final report for the project.
writeup.pdf: 
	pdflatex writeup.tex

report.pdf: figures/df.png  
	R -e "rmarkdown::render(\"writeup.Rmd\", output_format=\"pdf_document\")"
